/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatyup;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abenezer Ashenafi
 */
public class ChatClientHome extends javax.swing.JFrame {

    /**
     * Creates new form ChatClientHome 
     */
    private String ipaddress;//ip address of the user client
    private String username;//user name of a client
    private Socket socket;//socket connection of the client
    private int localtimer;//logical clock timer for the client
    //private DataInputStream reader;
    //private DataOutputStream writer;
    private BufferedReader reader;//bufferedreader object to read from the server 
    private PrintWriter writer;//
    
    /**
     * Creates new form ChatClientHome this method is a constructor 
     * setting the object variables with values
     */
    
    public ChatClientHome(String username,Socket socket,String ipaddress,int ltime)
     {
         try{
        initComponents();
        this.username=username;
        this.ipaddress=ipaddress;
        this.socket=socket;
        this.localtimer=ltime;
        this.reader=new BufferedReader(new InputStreamReader(socket.getInputStream()));
        this.writer=new PrintWriter(socket.getOutputStream());
        usernamevalue.setText(username);
        ipvalue.setText(ipaddress);
         new Read().start();
                }catch(IOException e)
                {
                    System.out.println(e+"error has been handled");
                }
    }
    class Read extends Thread{
     @Override
            public void run() {
                
                while(socket.isConnected())
                {
                    
                    String message;
                String y = null;
                String msg=null;
                String timer[]=null;
                int i=0;
                int m;
                    
                    try{
                        message=reader.readLine();
                        String[] timers=message.split("#");
       
        for (String x:timers){
            if(i==0){
            y=x;
            }
            else
            {
            msg=x;
            break;
            }
            i++;
        }
       
       
        m=Integer.parseInt(y);
        if(localtimer>=m){
        localtimer=localtimer+1;
        }
        else{
        localtimer=m+1;
        }
                         message=localtimer+"#"+msg;
                         msgdisplay.setForeground(Color.RED);
                         msgdisplay.append(""+ msg+ "\n");
                        System.out.println(message);
                        
                        
                    }catch(IOException e)
                    {
                        System.out.println("zxc");
                       // close(socket,reader,writer);
                    }
                    
                }
            }
}
    
 
    
    
    public ChatClientHome()
     {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainpage = new javax.swing.JPanel();
        leftcontainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgdisplay = new javax.swing.JTextArea();
        messageinput = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        rightcontainer = new javax.swing.JPanel();
        activeList = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ipaddresstitle = new javax.swing.JLabel();
        usernamevalue = new javax.swing.JLabel();
        usernametitle = new javax.swing.JLabel();
        ipvalue = new javax.swing.JLabel();
        statustitle = new javax.swing.JLabel();
        statusvalue = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        disconnect = new javax.swing.JButton();
        changepic = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        actvve = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setBackground(new java.awt.Color(29, 28, 42));

        jLabel1.setBackground(new java.awt.Color(29, 28, 42));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatyup/logobig.JPG"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainpage.setBackground(new java.awt.Color(29, 29, 36));

        msgdisplay.setColumns(20);
        msgdisplay.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        msgdisplay.setRows(5);
        jScrollPane1.setViewportView(msgdisplay);

        messageinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageinputActionPerformed(evt);
            }
        });

        send.setBackground(new java.awt.Color(0, 0, 0));
        send.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        send.setBorder(new javax.swing.border.MatteBorder(null));
        send.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorder(new javax.swing.border.MatteBorder(null));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        message.setText("Message:");

        javax.swing.GroupLayout leftcontainerLayout = new javax.swing.GroupLayout(leftcontainer);
        leftcontainer.setLayout(leftcontainerLayout);
        leftcontainerLayout.setHorizontalGroup(
            leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftcontainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageinput)
                .addContainerGap())
            .addGroup(leftcontainerLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        leftcontainerLayout.setVerticalGroup(
            leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftcontainerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageinput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftcontainerLayout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rightcontainer.setBackground(new java.awt.Color(255, 255, 255));

        activeList.setBackground(new java.awt.Color(29, 28, 42));
        activeList.setForeground(new java.awt.Color(117, 232, 208));

        ipaddresstitle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ipaddresstitle.setText("IP Address:");

        usernamevalue.setText("Abenezer Ashenafi");

        usernametitle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        usernametitle.setText("User Name:");

        ipvalue.setText("127.0.0.1");

        statustitle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        statustitle.setText("Status:");

        statusvalue.setText("Connected");

        avatar.setBackground(new java.awt.Color(255, 255, 255));
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatyup/man.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(153, 153, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        disconnect.setBackground(new java.awt.Color(0, 0, 0));
        disconnect.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        disconnect.setForeground(new java.awt.Color(255, 255, 255));
        disconnect.setText("Disconnect");
        disconnect.setBorder(new javax.swing.border.MatteBorder(null));
        disconnect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectActionPerformed(evt);
            }
        });

        changepic.setBackground(new java.awt.Color(0, 0, 0));
        changepic.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        changepic.setForeground(new java.awt.Color(255, 255, 255));
        changepic.setText("change");
        changepic.setBorder(new javax.swing.border.MatteBorder(null));
        changepic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        changepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepicActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(153, 153, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statustitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ipaddresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ipvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernametitle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernamevalue, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(avatar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(changepic, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(changepic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernametitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamevalue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipaddresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statustitle)
                    .addComponent(statusvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        activeList.addTab("Profile", jPanel1);

        javax.swing.GroupLayout actvveLayout = new javax.swing.GroupLayout(actvve);
        actvve.setLayout(actvveLayout);
        actvveLayout.setHorizontalGroup(
            actvveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        actvveLayout.setVerticalGroup(
            actvveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        activeList.addTab("Active List", actvve);

        javax.swing.GroupLayout rightcontainerLayout = new javax.swing.GroupLayout(rightcontainer);
        rightcontainer.setLayout(rightcontainerLayout);
        rightcontainerLayout.setHorizontalGroup(
            rightcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightcontainerLayout.createSequentialGroup()
                .addComponent(activeList, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        rightcontainerLayout.setVerticalGroup(
            rightcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activeList)
        );

        javax.swing.GroupLayout mainpageLayout = new javax.swing.GroupLayout(mainpage);
        mainpage.setLayout(mainpageLayout);
        mainpageLayout.setHorizontalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftcontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightcontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainpageLayout.setVerticalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftcontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainpageLayout.createSequentialGroup()
                .addComponent(rightcontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageinputActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
    if(messageinput.getText().equals(""))
     {
         JOptionPane.showMessageDialog(this,"please enter the field");
            
     }
    
    else{    
        try{
            String message;
        message=messageinput.getText();
       
            
            message=localtimer+"#"+message;
            System.out.println(message);
            writer.println(message);
            msgdisplay.setForeground(Color.BLUE);
            msgdisplay.append("" + message +"\n");
            //System.out.println(message);
            writer.flush();
            messageinput.setText("");
        }catch(Exception e){
           // close(socket,reader,writer);
            System.out.println("zxf");
        }
        
        
    }
        
       
        

       
    }//GEN-LAST:event_sendActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        messageinput.setText("");


       
    }//GEN-LAST:event_clearActionPerformed

    private void disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectActionPerformed
        this.dispose();
        try {
            this.reader.close();
             this.writer.close();
            this.socket.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ChatClientHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new StartPage().setVisible(true);

        
    }//GEN-LAST:event_disconnectActionPerformed

    private void changepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changepicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatClientHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane activeList;
    private javax.swing.JPanel actvve;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton changepic;
    private javax.swing.JButton clear;
    private javax.swing.JPanel container;
    private javax.swing.JButton disconnect;
    private javax.swing.JLabel ipaddresstitle;
    private javax.swing.JLabel ipvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel leftcontainer;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel mainpage;
    private javax.swing.JLabel message;
    private javax.swing.JTextField messageinput;
    private javax.swing.JTextArea msgdisplay;
    private javax.swing.JPanel rightcontainer;
    private javax.swing.JButton send;
    private javax.swing.JLabel statustitle;
    private javax.swing.JLabel statusvalue;
    private javax.swing.JLabel usernametitle;
    private javax.swing.JLabel usernamevalue;
    // End of variables declaration//GEN-END:variables
}
